runtime: nodejs8

service: forms

handlers:
- url: /
  static_files: client/static/index.html
  upload: client/static/index.html
- url: /static
  static_dir: client/static
- url: /api/(.*)
  script: auto
